apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: mobility-b2c-back-listener
spec:
  serviceAccountName: sa-pipeline-trigger
  triggers:
    - name: build-trigger
      interceptors:
        - name: "CEL filter: only master brancher pushed"
          ref:
            name: "cel"
          params:
          - name: "filter"
            value: "body.ref in ['refs/heads/master']"
      bindings:
        - ref: build-binding
      template:
        ref: build-template
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: build-binding
spec:
  params:
    - name: gitrevision
      value: $(body.after)
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)
    - name: image-name 
      value: $(body.repository.name)/mobility-api
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: main
    - name: gitrepositoryurl
      description: The git repository url
    - name: image-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: mobility-b2c-back-run-
      spec:
        serviceAccountName: sa-pipeline-runner
        pipelineRef:
          name: build-gradle-jib
        params:
          - name: image-url
            value: docker.smt-dev-private-riders/$(tt.params.image-name)
          - name: revision
            value: $(tt.params.gitrevision)
          - name: git-url
            value: $(tt.params.gitrepositoryurl)
          - name: insecure-registry
            value: "true"
          - name: subdirectory
            value: $(tt.params.image-name)
          - name: argo-app-name
            value: "mobility-b2c-back-api"
          - name: gitops-url
            value: "http://gitea.gitea:3000/tekton/mobility-b2c-back-deploy.git"
        workspaces:
        - name: source
          persistentvolumeclaim:
            claimName: pvc-riders-build
        - name: gitops
          emptyDir: {}
