apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-frontend-buildah
spec:
  params:
    - name: git-url 
    - name: revision
      default: master
    - name: subdirectory
    - name: image-url 
    - name: tls-verify
      default: "false"
    - name: build-stage
      default: "dev"
  workspaces:
    - name: source 
    - name: gitops 
  tasks:
    - name: generate-id
      taskRef:
        name: generate-build-id
      params:
        - name: base-version
          value: $(params.build-stage)
    - name: clone-sources
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.revision)
        - name: subdirectory
          value: $(params.subdirectory)
      workspaces:
        - name: output
          workspace: source
    - name: build-image
      taskRef:
        name: buildah
      runAfter:
        - clone-sources
      params:
        - name: IMAGE
          value: $(params.image-url):$(tasks.generate-id.results.build-id)
        - name: TLSVERIFY
          value: $(params.tls-verify)
        - name: CONTEXT
          value: $(params.subdirectory)
      workspaces:
        - name: source
          workspace: source
    - name: deploy
      taskRef:
        name: deploy
      runAfter:
        - build-image
      params:
        - name: argo-app-name
          value: "mobility-front"
        - name: gitops-url
          value: "http://gitea.gitea:3000/tekton/mobility_front_deploy.git"
        - name: image-url
          value: $(params.image-url)
        - name: build-id
          value: $(tasks.generate-id.results.build-id)
      workspaces:
        - name: gitops
          workspace: gitops
