apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: mobility-b2c-back-build-
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
    name: build-gradle-jib
  params:
  - name: revision
    value: master
  - name: insecure-registry
    value: "true"
  - name: subdirectory
    value: "mobility-b2c-back"
  - name: git-url
    value: http://gitea.gitea:3000/tekton/mobility-b2c-back.git
  - name: image-url
    value: "docker.smt-dev-private-riders/mobility-b2c-back/mobility-api"
  - name: argo-app-name
    value: "mobility-b2c-back-api"
  - name: gitops-url
    value: "http://gitea.gitea:3000/tekton/mobility-b2c-back-deploy.git"
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: pvc-riders-build
  - name: gitops
    emptyDir: {}

