apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: argo-deploy-
spec:
  serviceAccountName: sa-pipeline-runner
  params:
  - name: argo-app-name
    value: "kw-mvn"
  - name: gitops-url
    value: "http://192.168.121.151:30079/scm/kbdev/kb-dev-deployments.git"
  - name: image-url
    value: "192.168.121.151:30005/dev/kb-dev"
  - name: build-id
    value: "dev"
  taskRef:
    name: deploy
    kind: Task
  workspaces:
    - name: gitops
      emptyDir: {}
